# Generated by Django 4.2.19 on 2025-04-06 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='设计稿名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('reviewing', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件URL')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件类型')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_files', to=settings.AUTH_USER_MODEL, verbose_name='设计师')),
            ],
            options={
                'verbose_name': '设计稿文件',
                'verbose_name_plural': '设计稿文件',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设计模板',
                'verbose_name_plural': '设计模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='样品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('file_url', models.URLField(max_length=500, verbose_name='图片URL')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='参考编号')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设计样品',
                'verbose_name_plural': '设计样品',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
                ('design_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='design.designfile', verbose_name='设计稿')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '设计稿审核',
                'verbose_name_plural': '设计稿审核',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('version_number', models.CharField(max_length=50, verbose_name='版本号')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件URL')),
                ('changelog', models.TextField(blank=True, null=True, verbose_name='变更记录')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
                ('design_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='design.designfile', verbose_name='设计稿')),
            ],
            options={
                'verbose_name': '设计稿版本',
                'verbose_name_plural': '设计稿版本',
                'ordering': ['-created_at'],
                'unique_together': {('design_file', 'version_number')},
            },
        ),
    ]
