# Generated by Django 4.2.19 on 2025-04-05 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('expired', '已过期')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_global', models.BooleanField(default=False, verbose_name='全局通知')),
                ('departments', models.JSONField(blank=True, default=list, help_text='部门名称列表，如 ["研发部", "市场部"]', verbose_name='部门范围')),
                ('roles', models.JSONField(blank=True, default=list, help_text='角色名称列表，如 ["admin", "manager"]', verbose_name='角色范围')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notices', to='users.user', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_key', models.CharField(max_length=100, unique=True, verbose_name='参数键')),
                ('param_value', models.TextField(verbose_name='参数值')),
                ('param_type', models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值'), ('json', 'JSON')], max_length=20, verbose_name='参数类型')),
                ('description', models.CharField(max_length=200, verbose_name='参数描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'db_table': 'sys_parameter',
                'ordering': ['param_key'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('query', '查询'), ('export', '导出'), ('import', '导入'), ('login', '登录'), ('logout', '登出')], max_length=20, verbose_name='操作类型')),
                ('operation_module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('operation_desc', models.CharField(max_length=200, verbose_name='操作描述')),
                ('operation_detail', models.TextField(blank=True, null=True, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.notice', verbose_name='公告')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '公告阅读记录',
                'verbose_name_plural': '公告阅读记录',
                'unique_together': {('user', 'notice')},
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='read_by',
            field=models.ManyToManyField(related_name='read_notices', through='system.NoticeReadRecord', to='users.user', verbose_name='已读用户'),
        ),
        migrations.CreateModel(
            name='HistoricalSystemParameter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('param_key', models.CharField(db_index=True, max_length=100, verbose_name='参数键')),
                ('param_value', models.TextField(verbose_name='参数值')),
                ('param_type', models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值'), ('json', 'JSON')], max_length=20, verbose_name='参数类型')),
                ('description', models.CharField(max_length=200, verbose_name='参数描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统参数')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user', verbose_name='创建人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 系统参数',
                'verbose_name_plural': 'historical 系统参数',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
