# Generated by Django 4.2.19 on 2025-04-08 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('content', models.TextField(verbose_name='告警内容')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('active', '活动'), ('resolved', '已解决'), ('ignored', '已忽略')], default='active', max_length=20, verbose_name='状态')),
                ('source', models.CharField(max_length=100, verbose_name='告警来源')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_comment', models.TextField(blank=True, null=True, verbose_name='处理说明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='创建人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_alerts', to='users.user', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '系统告警',
                'verbose_name_plural': '系统告警',
                'db_table': 'sys_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
